# define the build stage by pulling in node image


#create a work directory 
#copy package.json to the work directory
# run npm install 

#copy the contnets of current context to an app directory
#run npm build script

# define the runtime stage using nginx image
#copy conets of build stage to nginx's home directory /app/build/ /usr/share/nginx/html

#expose port 80 
# add entyr point command  ["nginx","-g","daemon off;"]